Parallel
stanford-futuredata/msketch pull request #5
Opened 2018-05-16 06:13 UTC by jialinding

Parallel merge bench and RandomSketch

2018-05-23 22:13 UTC, edgan8 requested changes

2018-05-23 23:31 UTC, jialinding commented on javamsketch/quantilebench/src/main/java/yahoo/QuantilesHelper.java
> +public class QuantilesHelper {
I only copied files when they were needed to get rid of an error.

2018-05-23 23:31 UTC, jialinding commented on javamsketch/quantilebench/src/main/java/sketches/TDigestSketch.java
> +    public QuantileSketch parallelMerge(ArrayList<QuantileSketch> sketches, int numThreads) {
Yee

2018-05-24 00:00 UTC, jialinding commented on javamsketch/quantilebench/src/main/java/sketches/RandomSketch.java
> +                Collections.sort(curBuffer);
Yeah that makes it more efficient when combining buffers. This is the way it's described in the paper and in the coolwanglu code.

2018-05-24 04:58 UTC, jialinding commented on javamsketch/quantilebench/src/main/java/sampling/SamplingUtil.java
> +final class SamplingUtil {
good point

2018-05-24 07:27 UTC, jialinding commented on javamsketch/quantilebench/src/main/java/sampling/SamplingUtil.java
> +final class SamplingUtil {
actually some functions still use SamplingUtil for non-sampling purposes

2018-05-24 08:06 UTC, jialinding commented on javamsketch/quantilebench/src/main/java/sampling/SamplingUtil.java
> +    public static final Random rand = new Random();
ok

2018-05-24 21:51 UTC, edgan8 approved these changes

2018-05-24 21:54 UTC, merged